dataset:
  name: &name dob_now_applications
  version: "{{ version }}"
  acl: public-read
  source:
    url:
      path: s3://edm-private/dob_now/DOB_Now_Job_Filing_Data_for_DCP_{{ version }}.csv
      subpath: ""
    options:
      - "AUTODETECT_TYPE=NO"
      - "EMPTY_STRING_AS_NULL=YES"
    geometry:
      SRS: null
      type: NONE

  destination:
    name: *name
    geometry:
      SRS: null
      type: NONE
    options:
      - "OVERWRITE=YES"
      - "PRECISION=NO"
    fields: []
    sql: null

  info:
    description: |
      DOB NOW job applications received from DOB via FTP
    url: ""
    dependents: []
