dataset:
  name: &name dob_now_applications
  version: "{{ version }}"
  acl: public-read
  source:
    script: *name
    options:
      - "AUTODETECT_TYPE=NO"
      - "EMPTY_STRING_AS_NULL=YES"
    geometry:
      SRS: null
      type: NONE

  destination:
    name: *name
    geometry:
      SRS: null
      type: NONE
    options:
      - "OVERWRITE=YES"
      - "PRECISION=NO"
    fields: []
    sql: null

  info:
    description: |
      DOB NOW job applications received from DOB via FTP
      the python handles the encoding of the source file which is not standard utf-8.
      Also the versioning of this file is based on the date received from DOB
    url: ""
    dependents: []
