name: Update Documentation

on:
  push:
    branches:
      - main
    paths:
      - 'library/*.py'
      - '.github/workflows/docs.yml'

jobs:
  deploy:
    runs-on: ubuntu-20.04
    env:
      RECIPE_ENGINE: ${{ secrets.RECIPE_ENGINE }}
      AWS_S3_ENDPOINT: ${{ secrets.AWS_S3_ENDPOINT }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_S3_BUCKET: edm-recipes

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Set up GDAL and poetry
      run: |
        apt update
        apt install -y gdal-bin libgdal-dev python3-gdal g++

    - name: Install Python dependencies, create docs
      run: |
        python3.8 -m pip install --upgrade pip
        python3.8 -m pip install .
        python3.8 -m pip install pdoc
        python3.8 -m pdoc -o docs --html --force library

    - name: Commit output
      uses: EndBug/add-and-commit@v6
      with:
        author_name: GitHub Action
        author_email: action@github.com
        message: "🎉 Update Documentation"
        add: 'docs/'
